name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches:
      - '**'
jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in the job
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          path: ./
          dockerfile: Docker/Dockerfile
          tags: latest
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}