name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches:
      - '**'
jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "efinder2"
          context: ./
          password: ${{ secrets.PAT }}
          file: Docker/Dockerfile
          tags: latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}